* Beispiel: Cloak of Darkness

dgdebug cod.dg stdlib.dg
cat sos.scr - | dgdebug sos.dg stdlib.dg
(das minus - gibt Kontrolle zum keyboard stdin)

* weitere Beispiele in directory ./examples
** ex101.dg (- ex338.dg)  ist Inform Doks Beispiel 101 (- 338)
dialog versions taken from
https://intfiction.org/t/inform-examples-tailored-for-dialog/44025
inform versions from
https://ganelson.github.io/inform-website/book/examples_numerical.html

** Craverly Heights
./examples/craverly_heights.dg
https://www.linusakesson.net/dialog/craverly/craverly_side_by_side.html
Walkthrough + Map
https://solutionarchive.com/game/id%2C10452/Craverly+Heights.html

** Flipping the map
./examples/flipping_the_map.dg
descr: https://intfiction.org/t/lets-learn-dialog-flipping-the-map/78683
Inform7 https://intfiction.org/t/trinity-esque-direction-flips/78673

** Attracts
./examples/joybooth.dg
see let's learn Dialog

* Dialog Engine
** Dialog manual
https://dialog-if.github.io/manual/dialog/1c03-dev/index.html

** Wiki
https://www.ifwiki.org/Dialog

** Test für Impossible Stairs
https://github.com/Dialog-IF/dialog/blob/main/test/impossible/Makefile
Auther Mathbrush https://www.ifwiki.org/Mathbrush
https://intfiction.org/t/impossible-stairs-postmortem-and-using-dialog/57172

* Let's learn Dialog
https://intfiction.org/t/lets-learn-dialog/78444/14
https://github.com/tzbits/learn-dialog

speziell Prison
https://github.com/tzbits/learn-dialog/blob/main/prison.dg
descr: https://intfiction.org/t/lets-learn-dialog-flipping-the-map/78683/10

Finite Switchable
https://intfiction.org/t/adjacent-to-let-s-learn-dialog-finite-switchable-game/78518
https://intfiction.org/t/lets-learn-dialog-finite-switchable-game/78500

* IFWiki Examples Dialog
https://intfiction.org/t/elevator-and-stairs-example-code/59887
https://www.ifwiki.org/Category:Examples_of_Dialog_code
https://www.ifwiki.org/Elevator_and_stairs_(Dialog_example)

* Daniel Stelzer
** Repos
https://bitbucket.org/dstelzer/workspace/projects/IF
https://bitbucket.org/dstelzer/workspace/repositories/

** speziell: Scott Adams
https://intfiction.org/t/experiment-scott-adams-to-dialog-translator/73119
https://bitbucket.org/dstelzer/scott-adams-dialog-translator/src/main/

* Howard M. Lewis Ship (hlship)
Clojurian
https://github.com/hlship/sanddancer-dialog

* Questions
** How to implement an action scene
** How to display the exits automatically

* Sound of Saalsberg
** General
New in town, Reinhold impressed by "Music of the Spheres" on his way to the city of Jena, gives you his house.
Deine Hausfrauenfähigkeiten waren nie gut.

** study

(you have long hair, Mozart of course notices without noticing that the others do not notice).

** kitchen
salt on table from the mines of Tinyhall up the river.
Die Niere brennt an, musst sie salzen damit dus essen kannst. Am Ende isst die Katze die Niere.

Schnitzel with noodles only eat the southerners, despite the city is Rome of the North.
bloom watered Flowers; take one of many -> verwelkt gleich, aber wurst.
        As Reinhold is not in today, you are going to eat your favourite things at Wulff's Canteen.

** vorraum
would not want to leave without wig, nor without eating.

** Turm
Mozart braucht seine Geige um bei der Vorlesung spielen zu können.

** Wulf
I know, he is a gifted genious, so is ist sister Konstanze. But he is a crocodile, out of this world.
Wrote a school for violin myself, but since his mother died, I do not have time anymore, must run canteen.

